# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Test Build Corne PIM447 Right'
on:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      branches: '["manna-harbour/zmk/zephyr-2.5+cdc-mkb-mouse-pim447+corne-central-right"]'
